Fix linking breakage for rv_histogram
Since mpool is used in more places, it is necessary to link it; otherwise,
the following errors appear.

/usr/bin/ld: build/riscv.o: in function `block_map_clear':
riscv.c:(.text+0x68): undefined reference to `mpool_free'
/usr/bin/ld: riscv.c:(.text+0x7a): undefined reference to `mpool_free'
/usr/bin/ld: build/riscv.o: in function `rv_delete':
riscv.c:(.text+0x25d): undefined reference to `mpool_destroy'
/usr/bin/ld: riscv.c:(.text+0x269): undefined reference to `mpool_destroy'
/usr/bin/ld: build/riscv.o: in function `rv_create':
riscv.c:(.text+0x593): undefined reference to `mpool_create'
/usr/bin/ld: riscv.c:(.text+0x5aa): undefined reference to `mpool_create'
collect2: error: ld returned 1 exit status